export const FeaturedProducts = [
  {
    id: 1,
    name: "Hapusa Himalayan Dry Gin",
    img: "/sula/featuredHapusa.jpg",
    slug: "hapusa-himalayan-dry-gin",
    category: "gin",
    description:
      "Hapusa is a premium Himalayan dry gin, distilled with foraged botanicals from the region, creating a bold and aromatic spirit. Juniper, known as Hapusa in Sanskrit, is what gives their gin its name as well as its wild smell and scent.  This scarce juniper berry, which grows close to the Himalayan snow line, offers a lovely framework around which the other botanicals are thoughtfully placed. To create a true voyage in a glass, these botanicals are imported from all around the nation, combining its many flavours, cuisines, and civilisations.  Your taste sensations go through the monsoon forests of Tamil Nadu, the banks of the Hooghly River, the pine forests of the Himalayas, and the verdant spice plantations of Goa.",

    background: "/backgrounds/Hapusa-Gin-lifestyle.jpeg",
  },
  {
    id: 2,
    name: "Greater Than London Dry Gin",
    img: "/sula/greaterThanFeatured.jpg",
    slug: "greater-than-london-dry-gin",
    category: "gin",
    description:
      "Greater Than is India’s first craft gin, featuring juniper-forward flavors with hints of citrus and spice, perfect for refreshing cocktails.",
  },
  {
    id: 3,
    name: "Sula Chenin Blanc",
    img: "/sula/cheninFeature.jpg",
    slug: "sula-chenin-blanc",
    category: "wines",
    description:
      "Chenin Blanc is a refreshing white wine known for its bright acidity and tropical fruit flavors. Perfect for warm summer days.",
  },
  {
    id: 4,
    name: "Sula Shiraz Cabernet",
    img: "/sula/shirazFeature.jpg",
    slug: "sula-shiraz-cabernet",
    category: "wines",
    description:
      "Shiraz Cabernet is a bold red wine with deep berry flavors, balanced tannins, and a rich, full-bodied texture.",
  },
  {
    id: 5,
    name: "Sula Tropical Rose",
    img: "/sula/tropicalFeature.jpg",
    slug: "sula-tropical-rose",
    category: "wines",
    description: "A refreshing and fruity rosé wine, perfect for summer days.",
  },
];

export const Bottles = [
  {
    id: 1,
    name: "Hapusa Himalayan Dry Gin",
    img: "/home/hapusa.png",
    featuredImg: "/sula/featuredHapusa.jpg",
    slug: "hapusa-himalayan-dry-gin",
    category: "gin",
    description:
      "Hapusa is a premium Himalayan dry gin, distilled with foraged botanicals from the region, creating a bold and aromatic spirit. Juniper, known as Hapusa in Sanskrit, is what gives their gin its name as well as its wild smell and scent.  This scarce juniper berry, which grows close to the Himalayan snow line, offers a lovely framework around which the other botanicals are thoughtfully placed. To create a true voyage in a glass, these botanicals are imported from all around the nation, combining its many flavours, cuisines, and civilisations.  Your taste sensations go through the monsoon forests of Tamil Nadu, the banks of the Hooghly River, the pine forests of the Himalayas, and the verdant spice plantations of Goa.",

    background: "/backgrounds/Hapusa-Gin-lifestyle.jpeg",
  },
  {
    id: 2,
    name: "Greater Than London Dry Gin",
    img: "/home/greaterthan.png",
    featuredImg: "/sula/featuredHapusa.jpg",
    slug: "greater-than-london-dry-gin",
    category: "gin",
    description:
      "Greater Than is India’s first craft gin, featuring juniper-forward flavors with hints of citrus and spice, perfect for refreshing cocktails.",
  },
  {
    id: 3,
    name: "Sula Chenin Blanc",
    img: "/sula/cheninBlanc.png",
    featuredImg: "/sula/featuredHapusa.jpg",
    slug: "sula-chenin-blanc",
    category: "wines",
    description:
      "Chenin Blanc is a refreshing white wine known for its bright acidity and tropical fruit flavors. Perfect for warm summer days.",
  },
  {
    id: 4,
    name: "Sula Shiraz Cabernet",
    img: "/sula/shirazCabernet.png",
    featuredImg: "/sula/featuredHapusa.jpg",
    slug: "sula-shiraz-cabernet",
    category: "wines",
    description:
      "Shiraz Cabernet is a bold red wine with deep berry flavors, balanced tannins, and a rich, full-bodied texture.",
  },
  {
    id: 6,
    name: "Sula Tropical Rose",
    img: "/sula/Tropical.png",
    featuredImg: "/sula/featuredHapusa.jpg",
    slug: "sula-tropical-rose",
    category: "wines",
    description: "A refreshing and fruity rosé wine, perfect for summer days.",
  },
  {
    id: 7,
    name: "Sula Brut",
    img: "/sula/brute.png",
    slug: "sula-brut",
    category: "wines",
    description:
      "A crisp sparkling wine with delicate bubbles and fresh notes.",
  },
  {
    id: 8,
    name: "Sula Seco",
    img: "/sula/seco.png",
    slug: "sula-seco",
    category: "wines",
    description: "A dry and elegant sparkling wine from Sula Vineyards.",
  },
  {
    id: 9,
    name: "Sula Sparkling Shiraz",
    img: "/sula/Sprakling.png",
    slug: "sula-sparkling-shiraz",
    category: "wines",
    description: "A sparkling red wine with bold flavors and a lively fizz.",
  },
  {
    id: 10,
    name: "Sula Zinfandel Rosé",
    img: "/sula/Rose.png",
    slug: "sula-zinfandel-rose",
    category: "wines",
    description: "A fruity and vibrant rosé with a hint of sweetness.",
  },
  {
    id: 11,
    name: "Sula Zinfandel Red",
    img: "/sula/Zinfadel.png",
    slug: "sula-zinfandel-red",
    category: "wines",
    description: "A rich and full-bodied red wine with deep berry notes.",
  },
  {
    id: 12,
    name: "Luxardo Maraschino Originale",
    img: "/sula/luxardo_maraschino_originale.png",
    slug: "luxardo-maraschino-originale",
    category: "liqueur",
    description:
      "A classic Italian liqueur made from marasca cherries, perfect for cocktails.",
    background: "/backgrounds/Maraschino-1.jpg",
  },
  {
    id: 13,
    name: "Luxardo Sambuca",
    img: "/sula/luxardo_sambuca-1.png",
    slug: "luxardo-sambuca",
    category: "liqueur",
    description: "A traditional anise-flavored liqueur from Italy.",
    background: "/backgrounds/sambucabg.jpg",
  },
  {
    id: 14,
    name: "Luxardo Bitter Rosso",
    img: "/sula/luxardo_bitter.png",
    slug: "luxardo-bitter-rosso",
    category: "liqueur",
    description: "A balanced and aromatic bitter liqueur for cocktails.",
    background: "/backgrounds/bitterbg.jpg",
  },
  {
    id: 15,
    name: "Luxardo Aperitivo",
    img: "/sula/luxardo_aperitivo.png",
    slug: "luxardo-aperitivo",
    category: "liqueur",
    description: "A refreshing and citrus-forward Italian aperitif.",
    background: "/backgrounds/aperitivobg.jpg",
  },
  {
    id: 16,
    name: "Luxardo Cherry Liqueur",
    img: "/sula/luxardo-cherry.png",
    slug: "luxardo-cherry-liqueur",
    category: "liqueur",
    description: "A rich cherry liqueur, perfect for classic cocktails.",
    background: "/backgrounds/chreey-bg.jpg",
  },
  {
    id: 17,
    name: "Luxardo Triple Sec",
    img: "/sula/luxardotriple.jpg",
    slug: "luxardo-triple-sec",
    category: "liqueur",
    description:
      "A high-quality orange liqueur used in cocktails like Margaritas.",
    background: "/backgrounds/triple-sec.jpg",
  },
  {
    id: 18,
    name: "Luxardo Hazelnut Liqueur",
    img: "/sula/angioletto.png",
    slug: "luxardo-hazelnut-liqueur",
    category: "liqueur",
    description: "A smooth and nutty liqueur, great for dessert cocktails.",
    background: "/home/vodka-bg.jpeg",
  },
  {
    id: 19,
    name: "Luxardo Absinthe Fata Verde",
    img: "/sula/absinthe.jpg",
    slug: "luxardo-absinthe-fata-verde",
    category: "liqueur",
    description: "A classic absinthe with a strong anise and herbal profile.",
    background: "/home/vodka-bg.jpeg",
  },
  {
    id: 20,
    name: "Luxardo Rhubarb Bitter",
    img: "/sula/rhubarb.jpg",
    slug: "luxardo-rhubarb-bitter",
    category: "liqueur",
    description: "A bittersweet rhubarb-based liqueur for unique cocktails.",
    background: "/home/vodka-bg.jpeg",
  },
];
